version: '3.7'

services: 
  back:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: /app/bin/docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: rails server -b 0.0.0.0
    env_file:
      - ./.env
